/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Catalogo;

import Controlador.CopiaPeliculaDAO;
import Controlador.PeliculaDAO;
import Modelo.CopiaPelicula;
import Modelo.Pelicula;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diana
 */
public class CopiasDePelicula extends javax.swing.JDialog {
    private Pelicula peliculaActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CopiasDePelicula.class.getName());
private final int idPelicula;  
private int idSucursalActual;
  private boolean datosGuardados = false; 
    /**
     * Creates new form CopiasDePelicula
     */
    public CopiasDePelicula(java.awt.Frame parent, boolean modal, int idPelicula, int idSucursalActual) {
        super(parent, modal);
        initComponents();
        this.idPelicula = idPelicula;
        this.idSucursalActual = idSucursalActual;
        this.setLocationRelativeTo(null);
        cargarDatosCopiaPelicula(this.idPelicula, this.idSucursalActual);
        
    }
 
    
    
    public final void cargarDatosCopiaPelicula(int idPelicula, int idSucursalActual) {
        PeliculaDAO peliculaDao = new PeliculaDAO();
        
        try {
            // 1. Cargar la información general de la Película (Catálogo)
            this.peliculaActual = peliculaDao.obtenerPeliculaPorId(idPelicula);

            if (peliculaActual != null) {
                // 2. Llenar las etiquetas del formulario con datos del Catálogo
                txt_ID_Pelicula.setText(String.valueOf(peliculaActual.getIdPelicula()));
                txt_titulo.setText(peliculaActual.getTitulo());
                txt_director.setText(peliculaActual.getDirector());
                // Muestra la sucursal actual (usando el parámetro)
                txt_sucursal.setText(String.valueOf(idSucursalActual)); 
                
                // 3. Cargar las copias individuales de esa Película en la tabla
                cargarCopiasEnTabla(idPelicula, idSucursalActual);
                
            } else {
                JOptionPane.showMessageDialog(this, "Película con ID " + idPelicula + " no encontrada.", "Error de Carga", JOptionPane.ERROR_MESSAGE);
                this.dispose(); // Cierra el formulario si no encuentra la película
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos de la película: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            // Manejo de log si es necesario
        }
    }
    private void cargarCopiasEnTabla(int idPelicula, int idSucursal) {
        CopiaPeliculaDAO copiaDao = new CopiaPeliculaDAO();
        
        // Usamos el método que desarrollamos previamente para obtener solo las copias 
        // relevantes para esta Película y esta Sucursal.
        List<CopiaPelicula> copias = copiaDao.obtenerCopiasPorPeliculaYSucursal(idPelicula, idSucursal); 
        
        // 1. Definir el modelo de la tabla
        String[] nombresColumnas = {"ID_Copia_Pelicula", "ID_Pelicula", "ID_Sucursal", "Estado"};
        DefaultTableModel model = new DefaultTableModel(nombresColumnas, 0); 
        
        // 2. Llenar el modelo con los datos de las copias
        for (CopiaPelicula copia : copias) {
            model.addRow(new Object[]{
                copia.getIdCopiaPelicula(),
                copia.getIdPelicula(),
                copia.getIdSucursal(),
                copia.getEstado()
            });
        }
        
        // 3. Asignar el modelo a la JTable del formulario
        tabla_copias_peliculas.setModel(model);
        
        // Opcional: Ajustar el ancho de las columnas
        if (tabla_copias_peliculas.getColumnModel().getColumnCount() > 0) {
            tabla_copias_peliculas.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabla_copias_peliculas.getColumnModel().getColumn(3).setPreferredWidth(120);
        }
    }
      public boolean isDatosGuardados() {
        return datosGuardados;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ID_Pelicula = new javax.swing.JLabel();
        txt_titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_director = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_sucursal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_copias_peliculas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("COPIAS DE LA PELICULA");

        jLabel1.setText("ID Pelicula:");

        jLabel2.setText("Titulo:");

        txt_ID_Pelicula.setText("...");

        txt_titulo.setText("...");

        jLabel3.setText("Director:");

        txt_director.setText("...");

        jLabel5.setText("ID_Sucursal");

        txt_sucursal.setText("...");

        tabla_copias_peliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Copia_Pelicula", "ID_Pelicula", "ID_Sucursal", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla_copias_peliculas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ID_Pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_director, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txt_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ID_Pelicula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_titulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_director))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_sucursal))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_copias_peliculas;
    private javax.swing.JLabel txt_ID_Pelicula;
    private javax.swing.JLabel txt_director;
    private javax.swing.JLabel txt_sucursal;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
