/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Catalogo;
import Modelo.Pelicula;
import javax.swing.JOptionPane;
/**
 *
 * @author Diana
 */
public class FormularioAltasPelicula extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioAltasPelicula.class.getName());
    private Pelicula pelicula;
    private boolean datosGuardados = false;
    /**
     * Creates new form FormularioAltasPelicula
     */
    public FormularioAltasPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Sugerencia: centrar la ventana al abrir
        this.setLocationRelativeTo(parent); 
    }
public Pelicula getPelicula() {
        return pelicula;
    }

    public boolean isDatosGuardados() {
        return datosGuardados;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_altasClientes = new javax.swing.JButton();
        caja_director = new javax.swing.JTextField();
        btn_cancelarRegistroCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caja_precioAlquiler = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        caja_costoAdquisicion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        caja_stockTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        caja_titulo = new javax.swing.JTextField();
        combo_categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("DD/MM/AAAA");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("REGISTRAR NUEVA PELICULA");

        jLabel3.setText("Director");

        btn_altasClientes.setBackground(new java.awt.Color(153, 255, 153));
        btn_altasClientes.setText("GUARDAR");
        btn_altasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altasClientesActionPerformed(evt);
            }
        });

        btn_cancelarRegistroCliente.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancelarRegistroCliente.setText("CANCELAR");
        btn_cancelarRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarRegistroClienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Datos Generales");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Finanzas");

        caja_precioAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_precioAlquilerActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio para venta al publico");

        caja_costoAdquisicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_costoAdquisicionActionPerformed(evt);
            }
        });

        jLabel13.setText("Alquiler (Diario)");

        jLabel14.setText("Stock Total");

        jLabel1.setText("Titulo");

        jLabel2.setText("Categoria");

        jLabel15.setText("Fecha de Registro");

        caja_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_tituloActionPerformed(evt);
            }
        });

        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Acción", "Aventura", "Ciencia Ficción", "Comedia", "Drama", "Fantasía", "Terror", "Musical", "Documental", "Otro" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelarRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_altasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja_precioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja_stockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja_titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                            .addComponent(caja_director, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(caja_costoAdquisicion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                        .addGap(244, 244, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(2, 2, 2)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(caja_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_precioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(caja_costoAdquisicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(9, 9, 9)
                .addComponent(caja_stockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancelarRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btn_altasClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_altasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altasClientesActionPerformed
        String tituloStr = caja_titulo.getText().trim();
        String directorStr = caja_director.getText().trim();
        String precioAlquilerStr = caja_precioAlquiler.getText().trim();
        String costoAdquisicionStr = caja_costoAdquisicion.getText().trim();
        String stockTotalStr = caja_stockTotal.getText().trim();
        String categoriaStr = combo_categoria.getSelectedItem() != null ? combo_categoria.getSelectedItem().toString() : "";


        // 2. Validar campos obligatorios
        if (tituloStr.isEmpty() || directorStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Título y el Director son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (categoriaStr.equals("Seleccione una opción") || categoriaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una Categoría.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (precioAlquilerStr.isEmpty() || costoAdquisicionStr.isEmpty() || stockTotalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos de Finanzas y Stock son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 3. Conversión de tipos críticos: Precios a double, Stock a int
            double precioAlquiler = Double.parseDouble(precioAlquilerStr);
            double costoAdquisicion = Double.parseDouble(costoAdquisicionStr);
            int stockTotal = Integer.parseInt(stockTotalStr);
            
            // 4. Crear el objeto Pelicula y asignar los valores
            pelicula = new Pelicula();

            pelicula.setTitulo(tituloStr);
            pelicula.setCategoria(categoriaStr);
            pelicula.setDirector(directorStr);
            pelicula.setPrecioAlquiler(precioAlquiler);
            pelicula.setCosteAdquisicion(costoAdquisicion);
            pelicula.setStockTotal(stockTotal);
            
            // 5. Marcar como guardado y cerrar
            datosGuardados = true;
            this.dispose(); // Cierra el JDialog

        } catch (NumberFormatException e) {
            // Este catch atrapa la falla si el usuario escribe letras en los campos numéricos
            JOptionPane.showMessageDialog(this, "El Precio de Alquiler, Precio de Venta y Stock Total deben contener solo números válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Captura cualquier otra excepción
            JOptionPane.showMessageDialog(this, "Error al crear el objeto Película: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error al crear objeto Pelicula", e);
        }
    }//GEN-LAST:event_btn_altasClientesActionPerformed

    private void btn_cancelarRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarRegistroClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarRegistroClienteActionPerformed

    private void caja_precioAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_precioAlquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_precioAlquilerActionPerformed

    private void caja_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_tituloActionPerformed

    private void caja_costoAdquisicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_costoAdquisicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_costoAdquisicionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_altasClientes;
    private javax.swing.JButton btn_cancelarRegistroCliente;
    private javax.swing.JTextField caja_costoAdquisicion;
    private javax.swing.JTextField caja_director;
    private javax.swing.JTextField caja_precioAlquiler;
    private javax.swing.JTextField caja_stockTotal;
    private javax.swing.JTextField caja_titulo;
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
