/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package Vista.Alquileres;

import Controlador.ClienteDAO;
import Controlador.PeliculaDAO;
import Modelo.Alquiler;
import Modelo.Cliente;
import Modelo.Pelicula;
import com.toedter.calendar.JDateChooser;
import java.text.ParseException;
/**
 *
 * @author Diana
 */
public class FormularioRealizarRenta extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioRealizarRenta.class.getName());
private boolean datosGuardados;
private Alquiler alquiler;
    /** Creates new form FormularioRealizarRenta */
    public FormularioRealizarRenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        java.util.Date hoy = new java.util.Date();
        dateDevolucion.setMinSelectableDate(hoy);
        mostrarFechaActual();
        dateDevolucion.setEnabled(false);
    }
    public boolean isDatosGuardados() {
    return datosGuardados;
}

public Alquiler getAlquiler() {
    return alquiler;
}
private void mostrarFechaActual() {
    // Definir el formato de fecha (DD/MM/AAAA)
    java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
    // Obtener la fecha de hoy
    String fechaHoy = dateFormat.format(new java.util.Date());
    // Establecer el texto en el JLabel
    txt_fechaRenta.setText(fechaHoy);
}

// Nuevo método en FormularioRealizarRenta.java
private void verificarHabilitacionFecha() {
    // 1. Obtener los textos de los campos de datos.
    String tituloPelicula = txt_TituloPelicula.getText().trim();
    String nombreCliente = txt_NombreCliente.getText().trim();
    
    final String VALOR_DEFECTO_LABEL = "...";
    
    // 2. Verificar si AMBOS tienen datos válidos.
    boolean peliculaSeleccionada = !tituloPelicula.isEmpty() && !tituloPelicula.equals(VALOR_DEFECTO_LABEL);
    boolean clienteSeleccionado = !nombreCliente.isEmpty() && !nombreCliente.equals(VALOR_DEFECTO_LABEL);
    
    // 3. Habilitar el JDateChooser y el botón RENTAR solo si AMBOS son verdaderos.
    if (peliculaSeleccionada && clienteSeleccionado) {
        dateDevolucion.setEnabled(true);
        btnRentar.setEnabled(true); // Opcional: también habilitar el botón de renta
    } else {
        dateDevolucion.setEnabled(false);
        dateDevolucion.setDate(null); // Limpiar la fecha seleccionada si se deshabilita
        btnRentar.setEnabled(false); // Opcional: desactivar el botón de renta
        jLabel30.setText("$0.00"); // Limpiar el costo final
    }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cajaBuscadorPelicula = new javax.swing.JTextField();
        btn_buscarPelicula = new javax.swing.JButton();
        txt_TituloPelicula = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Categoria = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Director = new javax.swing.JLabel();
        txt_AlquilerDiario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cajaBuscadorCliente = new javax.swing.JTextField();
        btn_buscadorCliente = new javax.swing.JButton();
        txt_Apellido1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_NombreCliente = new javax.swing.JLabel();
        txt_Apellido2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_fechaRenta = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dateDevolucion = new com.toedter.calendar.JDateChooser();
        btnRentar = new javax.swing.JButton();
        btn_cancelarRegistroCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("REGISTRAR NUEVA RENTA DE PELICULA");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("ID de Pelicula");

        cajaBuscadorPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaBuscadorPeliculaActionPerformed(evt);
            }
        });

        btn_buscarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/busqueda.png"))); // NOI18N
        btn_buscarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarPeliculaActionPerformed(evt);
            }
        });

        txt_TituloPelicula.setText("...");

        jLabel7.setText("Categoria");

        txt_Categoria.setText("...");

        jLabel13.setText("Alquiler (Diario)");

        jLabel9.setText("Director");

        txt_Director.setText("...");

        txt_AlquilerDiario.setText("...");

        jLabel3.setText("Titulo de la Pelicula");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Datos de Pelicula");

        jLabel23.setBackground(new java.awt.Color(0, 0, 204));
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("Realizar busqueda por titulo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_Director, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txt_TituloPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addComponent(txt_AlquilerDiario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cajaBuscadorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_buscarPelicula)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel23)))
                    .addContainerGap(10, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel1)
                    .addGap(7, 7, 7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cajaBuscadorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_TituloPelicula))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_Categoria)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Director))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_AlquilerDiario))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_buscarPelicula)
                            .addComponent(jLabel23)))
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        jLabel15.setText("Fecha de Registro");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("DD/MM/AAAA");

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel21.setText("ID de Cliente");

        cajaBuscadorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaBuscadorClienteActionPerformed(evt);
            }
        });

        btn_buscadorCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/busqueda.png"))); // NOI18N
        btn_buscadorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscadorClienteActionPerformed(evt);
            }
        });

        txt_Apellido1.setText("...");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Datos de Cliente");

        jLabel18.setText("Apellido2");

        jLabel19.setText("Nombre(s)");

        jLabel20.setText("Apellido 1");

        txt_NombreCliente.setText("...");

        txt_Apellido2.setText("...");

        jLabel22.setBackground(new java.awt.Color(0, 0, 204));
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Realizar busqueda por Nombre del Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cajaBuscadorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscadorCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addComponent(jLabel19)
                    .addComponent(txt_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txt_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscadorCliente)
                    .addComponent(cajaBuscadorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_NombreCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Apellido1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Apellido2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Costo Final de Renta");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("$00.00");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Información de Renta");

        txt_fechaRenta.setText("...");

        jLabel26.setText("Fecha de Renta");

        jLabel28.setText("Fecha de Devolución/Vencimiento");

        dateDevolucion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateDevolucionPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(txt_fechaRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fechaRenta))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)
                        .addGap(16, 16, 16)
                        .addComponent(dateDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRentar.setBackground(new java.awt.Color(153, 255, 153));
        btnRentar.setText("RENTAR");
        btnRentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentarActionPerformed(evt);
            }
        });

        btn_cancelarRegistroCliente.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancelarRegistroCliente.setText("CANCELAR");
        btn_cancelarRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarRegistroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(796, 796, 796)
                        .addComponent(btn_cancelarRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRentar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRentar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaBuscadorPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaBuscadorPeliculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaBuscadorPeliculaActionPerformed

    private void cajaBuscadorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaBuscadorClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaBuscadorClienteActionPerformed
private Pelicula peliculaActual;
    private void btnRentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentarActionPerformed
  java.util.Date fechaDevolucionUtil = dateDevolucion.getDate();
    System.out.print(cajaBuscadorPelicula.getText()+"ZY");
    if (fechaDevolucionUtil == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una Fecha de Devolución.", "Error de Datos", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    Alquiler nuevoAlquiler = new Alquiler();
    java.sql.Date fechaRentaSQL = null;
    try {
        // ID de Película (Reemplaza 'jTextField1' por el nombre real de tu componente si es diferente)
        int idPelicula = Integer.parseInt(cajaBuscadorPelicula.getText()); 
        nuevoAlquiler.setIdPelicula(idPelicula);
        
        // ID de Cliente (cajaBuscadorCliente)
        int idCliente = Integer.parseInt(cajaBuscadorCliente.getText());
        nuevoAlquiler.setIdCliente(idCliente);
        System.out.print(cajaBuscadorPelicula.getText()+"ZYsEMANDO **********************");
        // Formato para parsear la fecha del JLabel (Ej: 21/11/2025)
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String fechaRentaStr = txt_fechaRenta.getText(); 
        java.util.Date fechaRentaUtil = dateFormat.parse(fechaRentaStr);
        
        // Conversión final a java.sql.Date
        fechaRentaSQL = new java.sql.Date(fechaRentaUtil.getTime());
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: El ID de Película o Cliente no es un número válido.", "Error de Datos", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    } catch (NullPointerException e) {
        // Atrapa si alguno de los campos de texto no existe (si el nombre es incorrecto)
        javax.swing.JOptionPane.showMessageDialog(this, "Error de Sistema: Revise que los campos de ID de Película y Cliente existan y estén bien nombrados.", "Error de Componentes", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }   catch (ParseException ex) {
            System.getLogger(FormularioRealizarRenta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    
    java.sql.Date fechaDevolucionSQL = new java.sql.Date(fechaDevolucionUtil.getTime());
    
    // Usamos java.util.Date en el Modelo
    nuevoAlquiler.setFechaAlquiler(fechaRentaSQL);
    nuevoAlquiler.setFechaDevolucion(fechaDevolucionSQL);
    nuevoAlquiler.setEstado("RENTADO");
    // Finalizar el proceso
    this.alquiler = nuevoAlquiler;
    this.datosGuardados = true;
    this.dispose();
    }//GEN-LAST:event_btnRentarActionPerformed
private void calcularCostoFinal() {
    // 1. Obtener Costo Diario (debe ser un valor numérico sin el '$')
    String costoDiarioTexto = txt_AlquilerDiario.getText().trim();
    double costoDiario = 0.0;
    
    if (costoDiarioTexto.equals("...")) {
        jLabel30.setText("$0.00");
        return;
    }
    
    try {
        int idPelicula = Integer.parseInt(cajaBuscadorPelicula.getText());
        costoDiario = Double.parseDouble(costoDiarioTexto);
    } catch (NumberFormatException e) {
        System.err.println("Error al convertir costo diario a número: " + e.getMessage());
        jLabel30.setText("ERROR");
        return;
    }

    // 2. Obtener Fechas
    java.util.Date fechaRenta = new java.util.Date(); // Hoy
    java.util.Date fechaDevolucion = dateDevolucion.getDate(); 
    
    if (fechaDevolucion == null || fechaDevolucion.before(fechaRenta)) {
        jLabel30.setText("$0.00");
        return;
    }
    
    // 3. Calcular Días (redondeando hacia arriba)
    long diferenciaMilisegundos = fechaDevolucion.getTime() - fechaRenta.getTime();
    double diferenciaDiasDecimal = (double) diferenciaMilisegundos / (1000 * 60 * 60 * 24);
    int numeroDias = (int) Math.ceil(diferenciaDiasDecimal);
    
    if (numeroDias < 1) {
        numeroDias = 1; 
    }

    // 4. Calcular, Formatear y Mostrar
    double costoTotal = costoDiario * numeroDias;
    String costoTotalFormateado = String.format("$%.2f", costoTotal);
    jLabel30.setText(costoTotalFormateado);
}
    private void btn_cancelarRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarRegistroClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarRegistroClienteActionPerformed

    private void btn_buscarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarPeliculaActionPerformed
     // 1. Obtener el ID ingresado
    String idTexto = cajaBuscadorPelicula.getText().trim();
    
    if (idTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la película.", "Error de Búsqueda", javax.swing.JOptionPane.WARNING_MESSAGE);
        limpiarDatosPelicula(); // Método para limpiar los JLabel si está vacío
        return;
    }
    
    try {
        // 2. Convertir el texto del ID a un número entero
        int idPelicula = Integer.parseInt(idTexto);
        
        // 3. Crear una instancia del DAO y buscar la película
        PeliculaDAO peliculaDAO = new PeliculaDAO(); 
        Pelicula peliculaEncontrada = peliculaDAO.obtenerPeliculaPorId(idPelicula);
        
        // 4. Verificar el resultado de la búsqueda
        if (peliculaEncontrada != null) {
            // A. PELÍCULA ENCONTRADA: Cargar los datos en los JLabel
            cargarDatosPelicula(peliculaEncontrada);
            javax.swing.JOptionPane.showMessageDialog(this, "Película cargada exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            // B. PELÍCULA NO ENCONTRADA: Mostrar error y limpiar
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ninguna película con el ID: " + idPelicula, "Película No Encontrada", javax.swing.JOptionPane.ERROR_MESSAGE);
            limpiarDatosPelicula();
        }
        
    } catch (NumberFormatException e) {
        // Manejar error si el usuario no ingresó un número
        javax.swing.JOptionPane.showMessageDialog(this, "El ID de Película debe ser un número válido.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarDatosPelicula();
    } catch (Exception e) {
        // Manejar cualquier otro error (ej. error de conexión a DB)
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar en la base de datos: " + e.getMessage(), "Error de Sistema", javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarDatosPelicula();
    }
    }//GEN-LAST:event_btn_buscarPeliculaActionPerformed

    private void btn_buscadorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscadorClienteActionPerformed
       String idTexto = cajaBuscadorCliente.getText().trim();
    
    if (idTexto.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el ID del cliente.", "Error de Búsqueda", javax.swing.JOptionPane.WARNING_MESSAGE);
        limpiarDatosCliente(); // Limpiar los JLabel si el campo está vacío
        return;
    }
    
    try {
        // 2. Convertir el texto del ID a un número entero
        int idCliente = Integer.parseInt(idTexto);
        
        // 3. Crear una instancia del DAO y buscar el cliente
        ClienteDAO clienteDAO = new ClienteDAO(); 
        Cliente clienteEncontrado = clienteDAO.obtenerClientePorId(idCliente); // Debes crear este método en tu DAO
        
        // 4. Verificar el resultado de la búsqueda
        if (clienteEncontrado != null) {
            // A. CLIENTE ENCONTRADO: Cargar los datos en los JLabel
            cargarDatosCliente(clienteEncontrado);
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente cargado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            // B. CLIENTE NO ENCONTRADO: Mostrar error y limpiar
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró ningún cliente con el ID: " + idCliente, "Cliente No Encontrado", javax.swing.JOptionPane.ERROR_MESSAGE);
            limpiarDatosCliente();
        }
        
    } catch (NumberFormatException e) {
        // Manejar error si el usuario no ingresó un número
        javax.swing.JOptionPane.showMessageDialog(this, "El ID de Cliente debe ser un número válido.", "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarDatosCliente();
    } catch (Exception e) {
        // Manejar cualquier otro error (ej. error de conexión a DB)
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar en la base de datos: " + e.getMessage(), "Error de Sistema", javax.swing.JOptionPane.ERROR_MESSAGE);
        limpiarDatosCliente();
    }
    }//GEN-LAST:event_btn_buscadorClienteActionPerformed

    private void dateDevolucionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateDevolucionPropertyChange
      if ("date".equals(evt.getPropertyName())) {
        calcularCostoFinal();
    }
    }//GEN-LAST:event_dateDevolucionPropertyChange

    private void cargarDatosCliente(Cliente c) {
    // Asigna los datos del Cliente (c) a los JLabel de la interfaz
    txt_NombreCliente.setText(c.getNombre());
    txt_Apellido1.setText(c.getApellido1()); 
    txt_Apellido2.setText(c.getApellido2()); 
    verificarHabilitacionFecha();
}
    private  void limpiarDatosCliente() {
    // Restablece los JLabel a su valor por defecto ("...")
    txt_NombreCliente.setText("...");
    txt_Apellido1.setText("...");
    txt_Apellido2.setText("...");
    verificarHabilitacionFecha();
}
    
    
    private void cargarDatosPelicula(Pelicula p) {
    // Asigna los datos de la Pelicula (p) a los JLabel de la interfaz
    txt_TituloPelicula.setText(p.getTitulo());
    txt_Director.setText(p.getDirector());
    txt_Categoria.setText(p.getCategoria());
    
    // Suponiendo que el alquiler diario es un valor numérico
    txt_AlquilerDiario.setText(String.valueOf(p.getPrecioAlquiler())); 
    verificarHabilitacionFecha();
}
    private void limpiarDatosPelicula() {
    // Restablece los JLabel a su valor por defecto
    txt_TituloPelicula.setText("...");
    txt_Director.setText("...");
    txt_Categoria.setText("...");
    txt_AlquilerDiario.setText("...");
    verificarHabilitacionFecha();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRentar;
    private javax.swing.JButton btn_buscadorCliente;
    private javax.swing.JButton btn_buscarPelicula;
    private javax.swing.JButton btn_cancelarRegistroCliente;
    private javax.swing.JTextField cajaBuscadorCliente;
    private javax.swing.JTextField cajaBuscadorPelicula;
    private com.toedter.calendar.JDateChooser dateDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txt_AlquilerDiario;
    private javax.swing.JLabel txt_Apellido1;
    private javax.swing.JLabel txt_Apellido2;
    private javax.swing.JLabel txt_Categoria;
    private javax.swing.JLabel txt_Director;
    private javax.swing.JLabel txt_NombreCliente;
    private javax.swing.JLabel txt_TituloPelicula;
    private javax.swing.JLabel txt_fechaRenta;
    // End of variables declaration//GEN-END:variables

}
