/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Alquileres;

import Controlador.AlquilerDAO; 
import Modelo.Alquiler;     
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.Pelicula;
import Vista.Alquileres.FormularioRealizarRenta;
/**
 *
 * @author Diana
 */
public class Panel_Alquileres extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Alquileres
     */
    public Panel_Alquileres() {
        initComponents();
        cargarAlquileresATabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Encabezado_Alquileres = new javax.swing.JPanel();
        txt_alquileres = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbla_alquileres = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnl_Encabezado_Alquileres.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Encabezado_Alquileres.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_Encabezado_Alquileres.setMinimumSize(new java.awt.Dimension(0, 50));
        pnl_Encabezado_Alquileres.setPreferredSize(new java.awt.Dimension(0, 40));
        pnl_Encabezado_Alquileres.setLayout(new java.awt.BorderLayout());

        txt_alquileres.setBackground(new java.awt.Color(255, 2, 255));
        txt_alquileres.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_alquileres.setMaximumSize(new java.awt.Dimension(32767, 40));
        txt_alquileres.setText("GESTIÓN DE ALQUILERES");
        pnl_Encabezado_Alquileres.add(txt_alquileres, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(184, 50));

        button1.setActionCommand("btn_nuevo");
        button1.setLabel("Nuevo");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        button1.getAccessibleContext().setAccessibleName("nuevo");

        pnl_Encabezado_Alquileres.add(jPanel1, java.awt.BorderLayout.LINE_END);

        add(pnl_Encabezado_Alquileres, java.awt.BorderLayout.NORTH);

        tbla_alquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Alquiler", "ID_Cliente", "ID_pelicula", "fecha_alquiler", "fecha_devolucion", "Estado", "Acciones(Editar/Eliminar)"
            }
        ));
        jScrollPane1.setViewportView(tbla_alquileres);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
   FormularioRealizarRenta form = new FormularioRealizarRenta(null, true);
        form.setVisible(true);

        // 2. Verificar si la renta fue exitosa y guardada
        if (form.isDatosGuardados()) {
            Alquiler nuevoAlquiler = form.getAlquiler(); 

            AlquilerDAO dao = new AlquilerDAO();

            // Asegúrate de que tu AlquilerDAO tenga un método 'insertarAlquiler'
            if (dao.insertarAlquiler(nuevoAlquiler)) {
                JOptionPane.showMessageDialog(this, "Renta registrada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // 3. Recargar la tabla para ver el nuevo registro
                cargarAlquileresATabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar la renta. Revise logs.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_button1ActionPerformed
public void cargarAlquileresATabla() {
        // Define el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel();

        // 1. Nombres de las columnas (deben coincidir con el initComponents)
        modelo.addColumn("ID_Alquiler");
        modelo.addColumn("ID_Cliente");
        modelo.addColumn("ID_Pelicula");
        modelo.addColumn("Fecha_Alquiler");
        modelo.addColumn("Fecha_Devolucion");
        modelo.addColumn("Estado");
        // La columna "Acciones" se manejaría con un renderizador/editor especial si se usa JTable,
        // pero para la carga de datos no se incluye en el modelo.

        AlquilerDAO dao = new AlquilerDAO();
        // Asegúrate de tener un método 'obtenerTodosLosAlquileres()' en tu AlquilerDAO
        List<Alquiler> alquileres = dao.obtenerTodosLosAlquileres();

        // 2. Llenar el modelo con los datos
        for (Alquiler a : alquileres) {
            // Se necesitan 6 columnas de datos, no 7, ya que Acciones es visual/funcional.
            Object[] fila = new Object[6]; 

            // Asegúrate que los getters de tu modelo Alquiler coincidan
            fila[0] = a.getIdAlquiler();
            fila[1] = a.getIdCliente();
            fila[2] = a.getIdPelicula();
            fila[3] = a.getFechaAlquiler();
            fila[4] = a.getFechaDevolucion();
            fila[5] = a.getEstado(); // Ej: "Rentado", "Devuelto", "Vencido"

            modelo.addRow(fila);
        }

        // 3. Asignar el modelo a la tabla
        tbla_alquileres.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_Encabezado_Alquileres;
    private javax.swing.JTable tbla_alquileres;
    private java.awt.Label txt_alquileres;
    // End of variables declaration//GEN-END:variables
}
