/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Alquileres;

import Controlador.AlquilerDAO; 
import Controlador.CopiaPeliculaDAO;
import Modelo.Alquiler;     
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Modelo.Pelicula;
import Vista.Alquileres.FormularioRealizarRenta;
/**
 *
 * @author Diana
 */
public class Panel_Alquileres extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Alquileres
     */
    public Panel_Alquileres() {
        initComponents();
        cargarAlquileresATabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Encabezado_Alquileres = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        btn_VistaCompleta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_alquileres = new java.awt.Label();
        btnDevolucion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbla_alquileres = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        pnl_Encabezado_Alquileres.setBackground(new java.awt.Color(204, 153, 255));
        pnl_Encabezado_Alquileres.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        pnl_Encabezado_Alquileres.setMinimumSize(new java.awt.Dimension(0, 50));
        pnl_Encabezado_Alquileres.setPreferredSize(new java.awt.Dimension(0, 40));
        pnl_Encabezado_Alquileres.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(284, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        button1.setActionCommand("btn_nuevo");
        button1.setBackground(new java.awt.Color(204, 255, 204));
        button1.setLabel("Nuevo");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, java.awt.BorderLayout.EAST);
        button1.getAccessibleContext().setAccessibleName("nuevo");

        btn_VistaCompleta.setBackground(new java.awt.Color(204, 204, 255));
        btn_VistaCompleta.setText("VISTA_ALQUILERES_COMPLETO");
        btn_VistaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VistaCompletaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_VistaCompleta, java.awt.BorderLayout.WEST);

        pnl_Encabezado_Alquileres.add(jPanel1, java.awt.BorderLayout.LINE_END);

        txt_alquileres.setBackground(new java.awt.Color(255, 2, 255));
        txt_alquileres.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txt_alquileres.setMaximumSize(new java.awt.Dimension(32767, 40));
        txt_alquileres.setText("GESTIÓN DE ALQUILERES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txt_alquileres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txt_alquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnl_Encabezado_Alquileres.add(jPanel2, java.awt.BorderLayout.WEST);

        btnDevolucion.setBackground(new java.awt.Color(255, 204, 255));
        btnDevolucion.setText("Devolución de Peliculas");
        btnDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolucionActionPerformed(evt);
            }
        });
        pnl_Encabezado_Alquileres.add(btnDevolucion, java.awt.BorderLayout.CENTER);

        add(pnl_Encabezado_Alquileres, java.awt.BorderLayout.PAGE_START);

        tbla_alquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Alquiler", "ID_Cliente", "ID_pelicula", "fecha_alquiler", "fecha_devolucion", "Estado", "Tarifa Final"
            }
        ));
        jScrollPane1.setViewportView(tbla_alquileres);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
   FormularioRealizarRenta form = new FormularioRealizarRenta(null, true);
    form.setVisible(true);

    // 2. Verificar si la renta fue exitosa y guardada
    if (form.isDatosGuardados()) {
        Alquiler nuevoAlquiler = form.getAlquiler(); // Contiene el ID de la copia
        AlquilerDAO daoAlquiler = new AlquilerDAO();
        
        // 1. Intentar insertar la Renta en la tabla ALQUILER
        if (daoAlquiler.insertarAlquiler(nuevoAlquiler)) {
            
            // 2. LÓGICA CLAVE: Actualizar el estado de la Copia
            int idCopiaRentada = nuevoAlquiler.getIdCopia(); 
            
            // 🚨 Debes crear y usar el DAO de la copia aquí
            CopiaPeliculaDAO daoCopia = new CopiaPeliculaDAO(); 
            
            // Ejecutar el UPDATE que dispara los TRIGGERS
            boolean estadoCambiado = daoCopia.actualizarEstadoCopia(idCopiaRentada, "RENTADO"); 

            if (estadoCambiado) {
                // Éxito completo: Renta registrada y copia actualizada (triggers disparados)
                JOptionPane.showMessageDialog(this, "Renta registrada con éxito y copia actualizada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                // 3. Recargar la tabla para ver el nuevo registro
                cargarAlquileresATabla();
                
                // Si tienes una función para recargar el stock/copias, llámala aquí
                // recargarTablaPeliculas(); 
            } else {
                // Alerta de Consistencia: Renta registrada, pero la copia sigue "Disponible"
                JOptionPane.showMessageDialog(this, "Alerta: Renta registrada, pero falló el cambio de estado de la Copia ID: " + idCopiaRentada + ". Revise logs y base de datos.", "Alerta de Consistencia", JOptionPane.WARNING_MESSAGE);
                // NOTA: En un sistema robusto, se debería intentar hacer un ROLLBACK de la renta.
            }
        } else {
            // Fallo en la inserción de la renta (error en el Stored Procedure o DB)
            JOptionPane.showMessageDialog(this, "Error al registrar la renta. Revise logs.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_button1ActionPerformed

    private void btn_VistaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VistaCompletaActionPerformed
   int idSucursalDelUsuario = 0; 
    
    // 1. Crear la instancia del nuevo Dialog
    Vista_AlquileresCompletos vista = new Vista_AlquileresCompletos(
        (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), // Parent
        true, // Modal
        idSucursalDelUsuario
    );
    
    // 2. Mostrar la ventana
    vista.setVisible(true);
    }//GEN-LAST:event_btn_VistaCompletaActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
  FormularioDevolverPelicula vistaDevolucion = new FormularioDevolverPelicula( (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true);
    vistaDevolucion.setVisible(true);
    }//GEN-LAST:event_btnDevolucionActionPerformed
public void cargarAlquileresATabla() {
        // Define el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel();

        // 1. Nombres de las columnas (deben coincidir con el initComponents)
        modelo.addColumn("ID_Alquiler");
        modelo.addColumn("ID_Cliente");
        modelo.addColumn("ID_Pelicula");
        modelo.addColumn("Fecha_Alquiler");
        modelo.addColumn("Fecha_Devolucion");
        modelo.addColumn("Estado");
         modelo.addColumn("Tarifa Final");
        // La columna "Acciones" se manejaría con un renderizador/editor especial si se usa JTable,
        // pero para la carga de datos no se incluye en el modelo.

        AlquilerDAO dao = new AlquilerDAO();
        // Asegúrate de tener un método 'obtenerTodosLosAlquileres()' en tu AlquilerDAO
        List<Alquiler> alquileres = dao.obtenerTodosLosAlquileres();

        // 2. Llenar el modelo con los datos
        for (Alquiler a : alquileres) {
            // Se necesitan 6 columnas de datos, no 7, ya que Acciones es visual/funcional.
            Object[] fila = new Object[7]; 

            // Asegúrate que los getters de tu modelo Alquiler coincidan
            fila[0] = a.getIdAlquiler();
            fila[1] = a.getIdCliente();
            fila[2] = a.getIdPelicula();
            fila[3] = a.getFechaAlquiler();
            fila[4] = a.getFechaDevolucion();
            fila[5] = a.getEstado(); // Ej: "Rentado", "Devuelto", "Vencido"
            fila[6] = String.format("$%.2f", a.getCostoFinal());

            modelo.addRow(fila);
        }

        // 3. Asignar el modelo a la tabla
        tbla_alquileres.setModel(modelo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btn_VistaCompleta;
    private java.awt.Button button1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_Encabezado_Alquileres;
    private javax.swing.JTable tbla_alquileres;
    private java.awt.Label txt_alquileres;
    // End of variables declaration//GEN-END:variables
}
