/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Alquileres;

import Controlador.AlquilerDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.AlquilerCompleto;
/**
 *
 * @author Diana
 */
public class Vista_AlquileresCompletos extends javax.swing.JDialog {
    private AlquilerDAO alquilerDao = new AlquilerDAO();
    private int idSucursalActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Vista_AlquileresCompletos.class.getName());

    public Vista_AlquileresCompletos(java.awt.Frame parent, boolean modal, int idSucursal) {
        super(parent, modal);
        initComponents();
        this.idSucursalActual = idSucursal;
        cargarTablaAlquileresVista(); 
    }
public void cargarTablaAlquileresVista() {
        // Usar la JTable de este nuevo Dialog
        DefaultTableModel modelo = (DefaultTableModel) tablaVistaAlquileres.getModel();
        
        // 1. Establecer las cabeceras de la VISTA (Nombres/Títulos)
        String[] nuevasColumnas = {"ID", "Cliente", "Película", "Alquiler", "Devolución", "Estado", "Tarifa"};
        modelo.setColumnIdentifiers(nuevasColumnas);
        modelo.setRowCount(0);

        // 2. Obtener los datos de la VISTA
        List<AlquilerCompleto> listado = alquilerDao.obtenerListadoAlquileres(this.idSucursalActual);
        
        // 3. Llenar la tabla
        for (AlquilerCompleto ac : listado) {
            Object[] fila = new Object[] {
                ac.getIdAlquiler(),
                ac.getNombreCliente(),   // VISTA: Nombre del Cliente
                ac.getTituloPelicula(),  // VISTA: Título de la Película
                ac.getFechaAlquiler(),
                ac.getFechaDevolucion(),
                ac.getEstado(),
                ac.getTarifaTotal()
            };
            modelo.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVistaAlquileres = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setText("VISTA_ALQUILERES_COMPLETO");
        getContentPane().add(label1);
        label1.setBounds(0, 10, 1168, 32);

        textArea1.setText("La vista realiza las siguientes uniones para vincular los datos:\n\nALQUILER A con PELICULA P: Se une por el campo ID_PELICULA para obtener el título de la película.\n\nALQUILER A con CLIENTES C: Se une por A.NO_CLIENTE = C.NO_CLIENTE para obtener los datos del cliente.");
        getContentPane().add(textArea1);
        textArea1.setBounds(10, 52, 639, 118);

        tablaVistaAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaVistaAlquileres);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 180, 980, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tablaVistaAlquileres;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
