/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Empleados;
import Modelo.Empleado;
import Controlador.EmpleadoDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author Diana
 */
public class ModificacionesEmpleado extends javax.swing.JDialog {
    private int idEmpleadoActual;
    private boolean datosGuardados = false; // Estado para el formulario principal
    private Empleado empleadoModificar; // Objeto a modificar
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificacionesEmpleado.class.getName());

    /**
     * Creates new form ModificacionesEmpleado
     */
    public ModificacionesEmpleado(java.awt.Frame parent, boolean modal, int idEmpleado) {
        super(parent, modal);
        initComponents();
        
        // Almacenar el ID y cargar los datos
        this.idEmpleadoActual = idEmpleado; 
        jLabel11.setText(String.valueOf(idEmpleado)); // Actualiza la etiqueta ID
        cargarDatosEmpleado(idEmpleado); // *DEBES IMPLEMENTAR ESTE MÉTODO*
    }
private void cargarDatosEmpleado(int id) {
    // 1. Crear el DAO
    // Asume que la clase EmpleadoDAO está importada y existe.
    Controlador.EmpleadoDAO dao = new Controlador.EmpleadoDAO(); 
    
    // 2. Obtener el objeto Empleado completo
    // Asume que tienes un método 'obtenerEmpleadoPorId' en tu DAO.
    empleadoModificar = dao.obtenerEmpleadoPorId(id); 

    if (empleadoModificar != null) {
        
        // 3. Llenar los campos del formulario con los datos obtenidos
        // (Datos Personales)
        caja_nombre.setText(empleadoModificar.getNombre());
        caja_apellido1.setText(empleadoModificar.getFName()); // Primer Apellido
        caja_apellido2.setText(empleadoModificar.getLName()); // Segundo Apellido
        
        // (Datos de Empresa/Rol)
        
        // Seleccionar la Categoría/Rol correcto en el JComboBox
        // Asume que el modelo de combo_rol contiene el valor exacto de empleadoModificar.getCategoria()
        combo_rol.setSelectedItem(empleadoModificar.getCategoria());
        
        // Seleccionar la Sucursal correcta en el JComboBox
        // Si el combo_sucursales usa Strings, debes obtener el String de la sucursal/ID.
        // Aquí se usa directamente el ID, pero quizás necesites un método que convierta el ID a un nombre de sucursal.
        // O: combo_sucursales.setSelectedItem(String.valueOf(empleadoModificar.getIdSucursal())); 
        // Si usas el ID de sucursal como String:
        combo_sucursales.setSelectedItem(String.valueOf(empleadoModificar.getIdSucursal()));
        
        // Opcional: Mostrar la fecha de modificación si tienes el campo
        // jLabel16.setText(formatoFecha(new Date())); 
        
    } else {
        // Manejo de error si no se encuentra el empleado
        JOptionPane.showMessageDialog(this, "Error: No se encontró el empleado con ID: " + id, "Error de Carga", JOptionPane.ERROR_MESSAGE);
        this.dispose(); // Cierra si no se puede cargar
    }
}
public boolean isDatosGuardados() { 
        return datosGuardados;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caja_nombre = new javax.swing.JTextField();
        caja_apellido1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        caja_apellido2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        combo_rol = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        combo_sucursales = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel15.setText("Fecha de Modificación");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("DD/MM/AAAA");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("MODIFICAR EMPLEADO");

        btn_guardar.setBackground(new java.awt.Color(153, 255, 153));
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("ID_Empleado:");

        jLabel11.setText("jLabel11");

        jLabel1.setText("Nombre(s)");

        jLabel2.setText("Apellido 1");

        caja_nombre.setText("jTextField1");
        caja_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_nombreActionPerformed(evt);
            }
        });

        caja_apellido1.setText("jTextField1");

        jLabel3.setText("Apellido2");

        caja_apellido2.setText("jTextField1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Datos Personales");

        combo_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Administrador", "Empleado" }));

        jLabel13.setText("Categoria/Rol");

        combo_sucursales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "0001", "0000", "0009" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Empresa");

        jLabel6.setText("Sucursal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel13)
                        .addComponent(combo_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_sucursales, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(caja_nombre)
                                .addComponent(caja_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(caja_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(caja_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(combo_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(28, 28, 28)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_sucursales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
    // -------------------------------------------------------------
    // 1. OBTENER DATOS DE LA VISTA
    // -------------------------------------------------------------
    String nombreStr = caja_nombre.getText().trim();
    String apellido1Str = caja_apellido1.getText().trim();
    String apellido2Str = caja_apellido2.getText().trim();
    String rolStr = combo_rol.getSelectedItem().toString();
    
    // Obtener el ID de Sucursal como String y convertirlo a INT para el modelo.
    String idSucursalStr = combo_sucursales.getSelectedItem().toString();
    int idSucursalInt;

    // -------------------------------------------------------------
    // 2. VALIDACIONES DE CAMPOS
    // -------------------------------------------------------------
    if (nombreStr.isEmpty() || apellido1Str.isEmpty() || apellido2Str.isEmpty() || idSucursalStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos los campos de texto son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (rolStr.equals("Seleccione una opción")) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una 'Categoría/Rol'.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (idSucursalStr.equals("Seleccione una opcion")) {
         JOptionPane.showMessageDialog(this, "Debe seleccionar una 'Sucursal'.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // -------------------------------------------------------------
    // 3. PROCESAMIENTO Y MODIFICACIÓN
    // -------------------------------------------------------------
    try {
        // Convertir el ID de Sucursal a int
        // ASUMIMOS que el item seleccionado en el combo es el ID (ej: "0001" -> 1)
        idSucursalInt = Integer.parseInt(idSucursalStr); 

        // 4. Actualizar el objeto empleadoModificar con los nuevos valores
        empleadoModificar.setNombre(nombreStr);
        empleadoModificar.setFName(apellido1Str);
        empleadoModificar.setLName(apellido2Str);
        empleadoModificar.setCategoria(rolStr);
        empleadoModificar.setIdSucursal(idSucursalInt);
        // El ID_Empleado (empleadoModificar.getIdEmpleado()) se mantiene.

        // 5. Llamar al DAO para modificar el empleado en la base de datos
        // Asegúrate de que tu DAO esté importado: import Controlador.EmpleadoDAO;
        Controlador.EmpleadoDAO dao = new Controlador.EmpleadoDAO();
        
        if (dao.modificarEmpleado(empleadoModificar)) {

            // **¡SOLUCIÓN AL ERROR isDatosGuardados()!**
            datosGuardados = true; 
            
            this.dispose(); // Cierra el formulario
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el empleado en la base de datos.", "Error de Modificación", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID de Sucursal debe ser un valor numérico válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        // Usa el logger que ya tienes en la clase:
        logger.severe("Error de formato al intentar parsear ID de Sucursal: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error inesperado al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        logger.severe("Error general al intentar modificar Empleado: " + e.getMessage());
    }

    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void caja_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField caja_apellido1;
    private javax.swing.JTextField caja_apellido2;
    private javax.swing.JTextField caja_nombre;
    private javax.swing.JComboBox<String> combo_rol;
    private javax.swing.JComboBox<String> combo_sucursales;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
