/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Configuracion;
import Controlador.UsuarioDAO;
import Modelo.Usuario;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
/**
 *
 * @author Diana
 */
public class ConfirmarCambiarContraseña extends javax.swing.JDialog {
    private UsuarioDAO usuarioDao = new UsuarioDAO();
    private Usuario usuarioActual;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConfirmarCambiarContraseña.class.getName());

    /**
     * Creates new form CambiarContraseña
     */
   public ConfirmarCambiarContraseña(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario);
        txtUsuario.setBounds(300, 220, 340, 30);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/candado.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(280, 320, 24, 24);

        txtClave.setText("jPasswordField1");
        jPanel2.add(txtClave);
        txtClave.setBounds(300, 320, 341, 24);

        btnIngresar.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Confirmar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar);
        btnIngresar.setBounds(490, 410, 150, 40);

        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Olvidaste tu Usuario?");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(510, 350, 140, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Cambiar Contraseña");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(290, 50, 390, 39);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(270, 220, 24, 24);

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ojo.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(640, 320, 24, 24);

        jLabel7.setText("Para continuar primero autentique el perfil");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(340, 110, 250, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Usuario");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(300, 200, 180, 16);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(300, 300, 180, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed

    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
      String user = txtUsuario.getText().trim();
    // Usar getPassword() y luego crear un String para obtener el texto
    String pass = new String(txtClave.getPassword()); 

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe ingresar la contraseña para confirmar.", "Error de Autenticación", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    Usuario usuarioAutenticado = usuarioDao.autenticar(user, pass); // Asegúrate que autenticar recibe el hash

    if (usuarioAutenticado != null) {
        // AUTENTICACIÓN EXITOSA

        // 3. Crear y mostrar la VISTA REAL DE CAMBIO DE CLAVE
        // Nota: Necesitas crear una nueva clase JDialog llamada VistaCambiarClaveReal.java
        CambiarClaves vistaCambio = new CambiarClaves((java.awt.Frame) this.getParent(), true, usuarioAutenticado);
        
        this.dispose(); // Cierra esta ventana de confirmación
        vistaCambio.setLocationRelativeTo(this.getParent());
        vistaCambio.setVisible(true);

    } else {
        // AUTENTICACIÓN FALLIDA
        JOptionPane.showMessageDialog(this, "Contraseña actual incorrecta.", "Error de Autenticación", JOptionPane.ERROR_MESSAGE);
        txtClave.setText(""); // Limpiar campo de clave
    }
    }//GEN-LAST:event_btnIngresarActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
