/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Sucursal;
import Modelo.Sucursal;
import Vista.Filtros.MaximoDigitosFilter;
import Vista.Filtros.SoloLetrasFilter;
import Vista.Filtros.SoloNumerosFilter;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import java.util.logging.Logger; // Importar Logger
import java.text.ParseException; // Importar ParseException si se necesitara

public class FormularioAltasSucursal extends javax.swing.JDialog {
    private Sucursal sucursal;
    private boolean datosGuardados = false; // Bandera para saber si se guardó
    // Utiliza el mismo logger
    private static final Logger logger = Logger.getLogger(FormularioAltasSucursal.class.getName());
   
    /**
     * Creates new form FormularioAltasSucursal
     */
    public FormularioAltasSucursal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Centrar la ventana al iniciar
        this.setLocationRelativeTo(null);
        Date fechaActual = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        String fechaStr = format.format(fechaActual);
        jLabel16.setText(fechaStr);
        
        // Filtros de Solo Letras para campos de texto largos
        SoloLetrasFilter letrasFilter = new SoloLetrasFilter();
        ((AbstractDocument) caja_nombreSucursal.getDocument()).setDocumentFilter(letrasFilter);
        ((AbstractDocument) caja_calle.getDocument()).setDocumentFilter(letrasFilter);
        ((AbstractDocument) caja_colonia.getDocument()).setDocumentFilter(letrasFilter);
        ((AbstractDocument) caja_ciudad.getDocument()).setDocumentFilter(letrasFilter);
        
        // Filtros de Solo Números/Dígitos y Máximo de Dígitos
        SoloNumerosFilter numerosFilter = new SoloNumerosFilter();
        
        // Teléfono: Permitir solo números (asumiendo CHAT(10) -> 10 dígitos)
        MaximoDigitosFilter telefonoFilter = new MaximoDigitosFilter(10);
        ((AbstractDocument) caja_Telefono.getDocument()).setDocumentFilter(telefonoFilter);
        ((AbstractDocument) caja_Telefono.getDocument()).setDocumentFilter(numerosFilter);
        
        // Número Exterior y CP: (CHAR(5)) -> 5 dígitos
        MaximoDigitosFilter char5Filter = new MaximoDigitosFilter(5);
        ((AbstractDocument) caja_num_exterior.getDocument()).setDocumentFilter(char5Filter);
        ((AbstractDocument) caja_CP.getDocument()).setDocumentFilter(char5Filter);
       
    }
    public Sucursal getSucursal() {
        return sucursal;
    }

    public boolean isDatosGuardados() {
        return datosGuardados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja_calle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        caja_CP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        combo_estados = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        caja_colonia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_altasClientes = new javax.swing.JButton();
        btn_cancelarRegistroCliente = new javax.swing.JButton();
        caja_ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        caja_num_exterior = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        caja_nombreSucursal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        caja_Telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        caja_calle.setText("jTextField1");

        jLabel8.setText("CP");

        caja_CP.setText("12345");

        jLabel9.setText("Estado");

        combo_estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opcion", "Zacatecas", "Jalisco", "Durango", " " }));
        combo_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_estadosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Datos Generales");

        jLabel12.setText("Nombre Sucursal");

        jLabel13.setText("NO_Exterior");

        jLabel14.setText("Colonia/Fraccionamiento");

        caja_colonia.setText("jTextField1");

        jLabel15.setText("Fecha de Registro");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("DD/MM/AAAA");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("REGISTRAR NUEVA SUCURSAL");

        btn_altasClientes.setBackground(new java.awt.Color(153, 255, 153));
        btn_altasClientes.setText("GUARDAR");
        btn_altasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altasClientesActionPerformed(evt);
            }
        });

        btn_cancelarRegistroCliente.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancelarRegistroCliente.setText("CANCELAR");
        btn_cancelarRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarRegistroClienteActionPerformed(evt);
            }
        });

        caja_ciudad.setText("jTextField2");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Domicilio");

        caja_num_exterior.setText("12");
        caja_num_exterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_num_exteriorActionPerformed(evt);
            }
        });

        jLabel6.setText("Calle");

        jLabel7.setText("Ciudad");

        caja_nombreSucursal.setText("1234567890");

        jLabel1.setText("Telefono");

        caja_Telefono.setText("1234567890");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(btn_cancelarRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_altasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(caja_colonia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(caja_calle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(caja_num_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_estados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(caja_ciudad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(caja_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(caja_nombreSucursal)
                                    .addComponent(jLabel1)
                                    .addComponent(caja_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_nombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(caja_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_num_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(caja_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addComponent(caja_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)
                        .addComponent(combo_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancelarRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_altasClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_estadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_estadosActionPerformed

    private void btn_altasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altasClientesActionPerformed
       String nombreSucursalStr = caja_nombreSucursal.getText().trim();
        String telefonoStr = caja_Telefono.getText().trim();
        int numExteriorStr =Integer.parseInt( caja_num_exterior.getText().trim());
        String calleStr = caja_calle.getText().trim();
        String coloniaStr = caja_colonia.getText().trim();
        String ciudadStr = caja_ciudad.getText().trim();
        String cpStr = caja_CP.getText().trim();
        String estadoStr = combo_estados.getSelectedItem().toString();

        if (nombreSucursalStr.isEmpty() || telefonoStr.isEmpty() || calleStr.isEmpty() || coloniaStr.isEmpty() || ciudadStr.isEmpty() || cpStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos de texto son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validar JComboBox (Estado)
        if (estadoStr.equals("Seleccione una Opcion")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un 'Estado'.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Crear el objeto Sucursal y asignar los valores
            sucursal = new Sucursal();
            
            // NO_Sucursal (es autoincremental, no se asigna aquí, solo se lee si se desea)
            // No se pide NO_Sucursal al usuario. El DAO lo recuperará después de la inserción.
            
            // Asignar los campos
            sucursal.setNombreSucursal(nombreSucursalStr);
            sucursal.setNoTelefono(telefonoStr);
            sucursal.setNumeroExterior(numExteriorStr); // CHAR(5) en DB, String en Modelo
            sucursal.setCalle(calleStr);
            sucursal.setColonia(coloniaStr);
            sucursal.setCiudad(ciudadStr);
            sucursal.setEstado(estadoStr);
            sucursal.setCp(cpStr); // CHAR(5) en DB, String en Modelo
            
            // 3. Marcar como guardado y cerrar
            datosGuardados = true;
            this.dispose(); // Cierra el JDialog
            
        } catch (NumberFormatException e) {
    // Manejar el error si el usuario no ingresó un número
    JOptionPane.showMessageDialog(this, "El número exterior debe ser un valor numérico entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
    return;
}catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear el objeto Sucursal: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.severe("Error al intentar crear objeto Sucursal: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_altasClientesActionPerformed

    private void btn_cancelarRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarRegistroClienteActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarRegistroClienteActionPerformed

    private void caja_num_exteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_num_exteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_num_exteriorActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_altasClientes;
    private javax.swing.JButton btn_cancelarRegistroCliente;
    private javax.swing.JTextField caja_CP;
    private javax.swing.JTextField caja_Telefono;
    private javax.swing.JTextField caja_calle;
    private javax.swing.JTextField caja_ciudad;
    private javax.swing.JTextField caja_colonia;
    private javax.swing.JTextField caja_nombreSucursal;
    private javax.swing.JTextField caja_num_exterior;
    private javax.swing.JComboBox<String> combo_estados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
