/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista.Sucursal;
import javax.swing.JOptionPane;
import Modelo.Sucursal; 
import Controlador.SucursalDAO; 
import java.awt.Frame; 
/**
 *
 * @author Diana
 */
public class ModificacionesSucursal extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificacionesSucursal.class.getName());
private short idSucursal;
    private boolean datosGuardados = false;
    private Sucursal sucursal; // Objeto para almacenar y modificar
    /**
     * Creates new form ModificacionesSucursal
     */
   public ModificacionesSucursal(java.awt.Frame parent, boolean modal, short idSucursal) {
       super(parent, modal);
        this.idSucursal = idSucursal;
        initComponents();
        this.setLocationRelativeTo(parent);
        cargarDatosSucursal();
    }
    public boolean isDatosGuardados() {
        return datosGuardados;
    }
private void cargarDatosSucursal() {
        SucursalDAO dao = new SucursalDAO();
        sucursal = dao.obtenerSucursalPorId(idSucursal);

        if (sucursal != null) {
            // Llenar los campos del formulario con los datos obtenidos
            caja_nombreSucursal.setText(sucursal.getNombreSucursal());
            caja_Telefono.setText(sucursal.getNoTelefono());
            caja_num_exterior.setText(String.valueOf(sucursal.getNumeroExterior()));
            caja_calle.setText(sucursal.getCalle());
            caja_colonia.setText(sucursal.getColonia());
            caja_ciudad.setText(sucursal.getCiudad());
            caja_CP.setText(sucursal.getCp());
            
            // Seleccionar el estado correcto en el JComboBox
            combo_estados.setSelectedItem(sucursal.getEstado());
            
            // Opcional: Mostrar la fecha de registro si tienes el campo
            // jLabel16.setText(formatoFecha(sucursal.getFechaRegistro())); 
            
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se encontró la sucursal con ID: " + idSucursal, "Error de Carga", JOptionPane.ERROR_MESSAGE);
            this.dispose(); // Cierra si no se puede cargar
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        caja_ciudad = new javax.swing.JTextField();
        combo_estados = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        caja_num_exterior = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        caja_nombreSucursal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        caja_Telefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        caja_colonia = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        caja_calle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        caja_CP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_cancelar.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jLabel9.setText("Estado");

        caja_ciudad.setText("jTextField2");

        combo_estados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una Opcion", "Zacatecas", "Jalisco", "Durango", " " }));
        combo_estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_estadosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Domicilio");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Datos Generales");

        caja_num_exterior.setText("12");
        caja_num_exterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_num_exteriorActionPerformed(evt);
            }
        });

        jLabel6.setText("Calle");

        jLabel7.setText("Ciudad");

        jLabel12.setText("Nombre Sucursal");

        caja_nombreSucursal.setText("1234567890");

        jLabel1.setText("Telefono");

        jLabel13.setText("NO_Exterior");

        caja_Telefono.setText("1234567890");

        jLabel14.setText("Colonia/Fraccionamiento");

        caja_colonia.setText("jTextField1");

        jLabel15.setText("Fecha de Registro");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("DD/MM/AAAA");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setText("MODIFICAR SUCURSAL");

        btn_guardar.setBackground(new java.awt.Color(153, 255, 153));
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        caja_calle.setText("jTextField1");

        jLabel8.setText("CP");

        caja_CP.setText("12345");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(caja_colonia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(caja_calle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(caja_num_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_estados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(caja_ciudad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(caja_CP, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(caja_nombreSucursal)
                                    .addComponent(jLabel1)
                                    .addComponent(caja_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_nombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(caja_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_num_exterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(caja_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(9, 9, 9)
                        .addComponent(caja_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(2, 2, 2)
                        .addComponent(combo_estados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caja_CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void combo_estadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_estadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_estadosActionPerformed

    private void caja_num_exteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_num_exteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_num_exteriorActionPerformed
 
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
                                           
        String nombreSucursalStr = caja_nombreSucursal.getText().trim();
        String telefonoStr = caja_Telefono.getText().trim();
        int numExteriorInt;
        String calleStr = caja_calle.getText().trim();
        String coloniaStr = caja_colonia.getText().trim();
        String ciudadStr = caja_ciudad.getText().trim();
        String cpStr = caja_CP.getText().trim();
        String estadoStr = combo_estados.getSelectedItem().toString();

        // 1. Validaciones
        if (nombreSucursalStr.isEmpty() || telefonoStr.isEmpty() || caja_num_exterior.getText().trim().isEmpty() || calleStr.isEmpty() || coloniaStr.isEmpty() || ciudadStr.isEmpty() || cpStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos de texto son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (estadoStr.equals("Seleccione una Opcion")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un 'Estado'.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Intentar convertir el Número Exterior a int
            numExteriorInt = Integer.parseInt(caja_num_exterior.getText().trim());

            // 2. Actualizar el objeto sucursal con los nuevos valores
            sucursal.setNombreSucursal(nombreSucursalStr);
            sucursal.setNoTelefono(telefonoStr);
            sucursal.setNumeroExterior(numExteriorInt); 
            sucursal.setCalle(calleStr);
            sucursal.setColonia(coloniaStr);
            sucursal.setCiudad(ciudadStr);
            sucursal.setEstado(estadoStr);
            sucursal.setCp(cpStr);
            // El ID (NoSucursal) se mantiene sin cambios
            
            // 3. Llamar al DAO para modificar la sucursal en la base de datos
            SucursalDAO dao = new SucursalDAO();
            if (dao.modificarSucursal(sucursal)) {
                
                datosGuardados = true; // Éxito
                this.dispose(); 
            } else {
                JOptionPane.showMessageDialog(this, "Error al modificar la sucursal en la base de datos.", "Error de Modificación", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número exterior y el CP deben ser valores numéricos válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            logger.severe("Error de formato al intentar parsear número: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.severe("Error general al intentar modificar Sucursal: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField caja_CP;
    private javax.swing.JTextField caja_Telefono;
    private javax.swing.JTextField caja_calle;
    private javax.swing.JTextField caja_ciudad;
    private javax.swing.JTextField caja_colonia;
    private javax.swing.JTextField caja_nombreSucursal;
    private javax.swing.JTextField caja_num_exterior;
    private javax.swing.JComboBox<String> combo_estados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
