/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Sucursal;

import javax.swing.JOptionPane;
import Modelo.Sucursal;
import Controlador.SucursalDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import java.awt.Frame; // Necesario para SwingUtilities.getWindowAncestor
import javax.swing.SwingUtilities; // Necesario para obtener el Frame padre
/**
 *
 * @author Diana
 */
public class PanelSucursales extends javax.swing.JPanel {

    /**
     * Creates new form PanelSucursales
     */
    public PanelSucursales() {
        initComponents();
        inicializarPopupMenu(); 
    agregarListeners();  
    cargarDatosTabla();
    }
    private JPopupMenu popupMenu; 
private JMenuItem menuItemModificar;
private JMenuItem menuItemEliminar;

private void inicializarPopupMenu() {
    popupMenu = new JPopupMenu();
    
    // Crear la opción Modificar
    menuItemModificar = new JMenuItem("Modificar Sucursal");
    popupMenu.add(menuItemModificar);
    
    // Crear la opción Eliminar
    menuItemEliminar = new JMenuItem("Eliminar Sucursal");
    popupMenu.add(menuItemEliminar);
    
    // Asignar el menú a tu JTable (asumo que tu tabla se llama 'tablaSucursales')
   // tablaSucursales.setComponentPopupMenu(popupMenu);
    
    // 2. Agregar Listeners (en el siguiente paso)
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSucursales = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        encabezado.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE SUCURSALES");
        encabezado.add(jLabel1, java.awt.BorderLayout.WEST);

        button1.setLabel("NUEVO");
        button1.setPreferredSize(new java.awt.Dimension(200, 24));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        encabezado.add(button1, java.awt.BorderLayout.LINE_END);

        add(encabezado, java.awt.BorderLayout.NORTH);

        tablaSucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Sucursal", "Nombre", "telefono", "NO.Exterior", "calle", "colonia", "ciudad", "estado", "CP"
            }
        ));
        jScrollPane1.setViewportView(tablaSucursales);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
FormularioAltasSucursal formSucursal = new FormularioAltasSucursal(null, true);
formSucursal.setVisible(true); // Bloquea la ventana principal hasta que se cierre

// 2. Verificar si el usuario presionó Guardar en el formulario
if (formSucursal.isDatosGuardados()) {
    // Obtener el objeto Sucursal lleno con los datos del formulario
    Sucursal nuevaSucursal = formSucursal.getSucursal();

    // Crear una instancia del objeto de Acceso a Datos
    SucursalDAO dao = new SucursalDAO();

    // 3. Intentar insertar la sucursal en la base de datos
    if (dao.insertarSucursal(nuevaSucursal)) {
        // Éxito: Mostrar mensaje y recargar la tabla de la ventana principal
        JOptionPane.showMessageDialog(this, "Sucursal insertada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        // 4. Recargar la tabla (método que debe existir en tu clase actual)
        cargarDatosTabla();
    } else {
        // Error: Mostrar mensaje de fallo
        JOptionPane.showMessageDialog(this, "Error al insertar la sucursal. Revisa logs.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed


private void agregarListeners() {
    menuItemModificar.addActionListener(new ActionListener() {
        @Override
      public void actionPerformed(ActionEvent e) {
            // Llama al método central de lógica, simplificando el ActionListener
            ejecutarModificarSucursal(); 
        }
    });

    menuItemEliminar.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int filaSeleccionada = tablaSucursales.getSelectedRow();
            if (filaSeleccionada != -1) {
                // Obtener el ID de la primera columna (columna 0)
                short idSucursal = (short) tablaSucursales.getValueAt(filaSeleccionada, 0);
                System.out.println("ID de Sucursal seleccionado para modificar: " + idSucursal);
                Frame framePadre = (Frame) SwingUtilities.getWindowAncestor(PanelSucursales.this);
                // Llamar al método de eliminación
                eliminarSucursal(idSucursal);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una sucursal para eliminar.");
            }
        }
    });
    tablaSucursales.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            // Verificar si es el evento que dispara el pop-up (clic derecho)
            if (evt.isPopupTrigger()) {
                int row = tablaSucursales.rowAtPoint(evt.getPoint());

                if (row != -1) {
                    // Forzar la selección de la fila bajo el cursor
                    tablaSucursales.setRowSelectionInterval(row, row);
                    
                    // Mostrar el menú en las coordenadas del clic
                    popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
                }
            }
        }
        
        // Es buena práctica manejar el mouseReleased también, ya que la detección
        // del Pop-up varía entre sistemas operativos (mousePressed o mouseReleased)
        @Override
        public void mouseReleased(java.awt.event.MouseEvent evt) {
             if (evt.isPopupTrigger()) {
                int row = tablaSucursales.rowAtPoint(evt.getPoint());

                if (row != -1) {
                    tablaSucursales.setRowSelectionInterval(row, row);
                    popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
                }
             }
        }
    });
}
    

private void eliminarSucursal(short idSucursal) {
    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro de que desea eliminar la sucursal con ID: " + idSucursal + "?", 
        "Confirmar Eliminación", 
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        SucursalDAO dao = new SucursalDAO();
        if (dao.eliminarSucursal(idSucursal)) {
            JOptionPane.showMessageDialog(this, "Sucursal eliminada exitosamente.");
            // Refrescar la tabla
            cargarDatosTabla(); 
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar la sucursal.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

private void ejecutarModificarSucursal() {
    int filaSeleccionada = tablaSucursales.getSelectedRow();
    System.out.println(filaSeleccionada);
    if (filaSeleccionada != -1) {
        // Obtener el ID
        short idSucursal = (short) tablaSucursales.getValueAt(filaSeleccionada, 0);
        
        // Obtener el Frame padre
        Frame framePadre = (Frame) SwingUtilities.getWindowAncestor(PanelSucursales.this);
        // 1. Abrir el formulario de Modificación (el JDialog)
        ModificacionesSucursal formModificar = new ModificacionesSucursal(framePadre, true, idSucursal);
        formModificar.setVisible(true);

        // 2. Verificar si se guardaron los datos al cerrar
        if (formModificar.isDatosGuardados()) {
            JOptionPane.showMessageDialog(this, "Sucursal modificada con éxito.");
            cargarDatosTabla(); // Recargar la tabla
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una sucursal para modificar.");
    }
}
private void cargarDatosTabla() {
    try {
        // 1. Definir el modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID_Sucursal"); // Usa el nombre de la columna que definiste en initComponents
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("NO.Exterior");
        modelo.addColumn("calle");
        modelo.addColumn("colonia");
        modelo.addColumn("ciudad");
        modelo.addColumn("estado");
        modelo.addColumn("CP");
        
        // 2. Obtener los datos actualizados
        SucursalDAO dao = new SucursalDAO();
        List<Modelo.Sucursal> listaSucursales = dao.obtenerTodasLasSucursales();

        // 3. Llenar el modelo con los nuevos datos
        for (Modelo.Sucursal s : listaSucursales) {
            modelo.addRow(new Object[]{
                s.getNoSucursal(),
                s.getNombreSucursal(),
                s.getNoTelefono(),
                s.getNumeroExterior(),
                s.getCalle(),
                s.getColonia(),
                s.getCiudad(),
                s.getEstado(),
                s.getCp()
            });
        }
        
        // 4. Asignar el nuevo modelo (con los datos) a la tabla
        tablaSucursales.setModel(modelo);
        
    } catch (Exception ex) {
        System.err.println("Error al cargar datos en la tabla: " + ex.getMessage());
        // Aquí podrías mostrar un JOptionPane de error de conexión o BD
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JPanel encabezado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSucursales;
    // End of variables declaration//GEN-END:variables
}
