/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.Sucursal;

import javax.swing.JOptionPane;
import Modelo.Sucursal;
import Controlador.SucursalDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Diana
 */
public class PanelSucursales extends javax.swing.JPanel {

    /**
     * Creates new form PanelSucursales
     */
    public PanelSucursales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSucursales = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        encabezado.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE SUCURSALES");
        encabezado.add(jLabel1, java.awt.BorderLayout.WEST);

        button1.setLabel("NUEVO");
        button1.setPreferredSize(new java.awt.Dimension(200, 24));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        encabezado.add(button1, java.awt.BorderLayout.LINE_END);

        add(encabezado, java.awt.BorderLayout.NORTH);

        tablaSucursales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Sucursal", "Nombre", "telefono", "NO.Exterior", "calle", "colonia", "ciudad", "estado", "CP"
            }
        ));
        jScrollPane1.setViewportView(tablaSucursales);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
FormularioAltasSucursal formSucursal = new FormularioAltasSucursal(null, true);
formSucursal.setVisible(true); // Bloquea la ventana principal hasta que se cierre

// 2. Verificar si el usuario presionó Guardar en el formulario
if (formSucursal.isDatosGuardados()) {
    // Obtener el objeto Sucursal lleno con los datos del formulario
    Sucursal nuevaSucursal = formSucursal.getSucursal();

    // Crear una instancia del objeto de Acceso a Datos
    SucursalDAO dao = new SucursalDAO();

    // 3. Intentar insertar la sucursal en la base de datos
    if (dao.insertarSucursal(nuevaSucursal)) {
        // Éxito: Mostrar mensaje y recargar la tabla de la ventana principal
        JOptionPane.showMessageDialog(this, "Sucursal insertada con éxito. ID: " + nuevaSucursal.getNoSucursal(), "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        // 4. Recargar la tabla (método que debe existir en tu clase actual)
        cargarSucursalesATabla();
    } else {
        // Error: Mostrar mensaje de fallo
        JOptionPane.showMessageDialog(this, "Error al insertar la sucursal. Revisa logs.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed
public void cargarSucursalesATabla() {
    DefaultTableModel modelo = new DefaultTableModel();

    // 1. Definir las columnas de la tabla de Sucursales
    // (Asegúrate de que estos nombres coincidan con los de tu JTable en el initComponents)
    modelo.addColumn("No_Sucursal");
    modelo.addColumn("Nombre Sucursal");
    modelo.addColumn("Teléfono");
    modelo.addColumn("NO_Exterior");
    modelo.addColumn("Calle");
    modelo.addColumn("Colonia");
    modelo.addColumn("Ciudad");
    modelo.addColumn("Estado");
    modelo.addColumn("CP");

    // Opcional: Si quieres mostrar la Fecha de Registro (aunque no está en el formulario de altas)
    // modelo.addColumn("Fecha_Registro"); 

    // 2. Obtener los datos usando el DAO
    SucursalDAO dao = new SucursalDAO();
    // Asumiendo que has implementado este método en tu SucursalDAO
    List<Sucursal> sucursales = dao.obtenerTodasLasSucursales();

    // 3. Llenar el modelo con los datos
    for (Sucursal s : sucursales) {
        // La cantidad de columnas debe coincidir con la definición de addColumn (9 columnas en este ejemplo)
        Object[] fila = new Object[9]; 

        fila[0] = s.getNoSucursal(); // Asumiendo que tienes getNoSucursal() en la clase Sucursal
        fila[1] = s.getNombreSucursal();
        fila[2] = s.getNoTelefono();
        fila[3] = s.getNumeroExterior();
        fila[4] = s.getCalle();
        fila[5] = s.getColonia();
        fila[6] = s.getCiudad();
        fila[7] = s.getEstado();
        fila[8] = s.getCp();
        // Si incluyes Fecha_Registro:
        // fila[9] = s.getFechaRegistro();

        modelo.addRow(fila);
    }

    // 4. Asignar el modelo a tu JTable
    // Asegúrate de que el nombre de tu tabla en PanelSucursales sea 'tbla_sucursales' o el que uses.
    tablaSucursales.setModel(modelo); 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JPanel encabezado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSucursales;
    // End of variables declaration//GEN-END:variables
}
