/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ClienteDAO;
import Modelo.Cliente;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diana
 */
public class Panel_Cliente extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Cliente
     */
    public Panel_Cliente() {
        initComponents();
        cargarClientesATabla();
    }
    
       private void cargarClientesATabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        
        // Nombres de las columnas de tu JTable (ajustar si son diferentes)
        modelo.addColumn("ID_Cliente");
        modelo.addColumn("Nombre");
        modelo.addColumn("Primer Ap");
        modelo.addColumn("Segundo Ap");
        modelo.addColumn("Calle");
        modelo.addColumn("Ciudad");
        modelo.addColumn("CP");
        modelo.addColumn("Estado"); // Incluir la nueva columna
        modelo.addColumn("Fecha_Reg");
        modelo.addColumn("No_Sucursal");
        
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> clientes = dao.obtenerTodosLosClientes();
        
        for (Cliente c : clientes) {
            Object[] fila = new Object[10]; // ¡Ahora son 10 columnas!
            
            fila[0] = c.getNoCliente();
            fila[1] = c.getNombre();
            fila[2] = c.getApellido1();
            fila[3] = c.getApellido2();
            fila[4] = c.getCalle();
            fila[5] = c.getCiudad();
            fila[6] = c.getCp();
            fila[7] = c.getEstado(); // Nuevo campo
            fila[8] = c.getFechaRegistro(); 
            fila[9] = c.getNoSucursal();
            
            modelo.addRow(fila);
        }
        
        tbla_clientes.setModel(modelo); // Asignar el modelo a la tabla
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbla_clientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tbla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Cliente", "Nombre", "Primer_Ap", "Segundo_Ap", "Calle", "Ciudad", "Estado", "CP", "Fecha_Registro", "No_Sucursal", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbla_clientes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE CLIENTES");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbla_clientes;
    // End of variables declaration//GEN-END:variables
}
